::
:: @file eventlog-forwarder.bat
:: @version v1.4
::
:: @url https://innovarew.appspot.com/
:: @author Innovarew <innovarew.solutions (at) gmail (dot) com>
:: @copyright (C) 2013 Innovarew Solutions. All Rights Reserved.
:: @license Proprietary and confidential
::     Unauthorized copying of this file, via any medium is strictly prohibited.
:: Contact us if you are interested in using our products and services.
::
:: Changelog:
::
:: [dd/mm/yyyy]        [author]
:: [brief description]
::
:: 21/01/2013        innovare.solutions
:: v1.0 Initial version
::
:: 15/02/2013        innovare.solutions
:: v1.1 Added TCP TLS support
::
:: 10/03/2013        innovare.solutions
:: v1.2 Added config eventlog-forwarder-config.bat
::
:: 08/04/2013        innovare.solutions
:: v1.3 Support forwarding several LogNames="Security,System" etc.
::
:: 14/04/2013        innovare.solutions
:: v1.4 Support forwarding regular application log files.
::

@echo off

:: Configurable options: edit eventlog-forwarder-config.bat
:: (do not edit this file, instead place settings in the config file)

:: Prevent double-click execution
if %0 == "%~0" (
    pause
)

:: Non-Configurable options
set cwd=%~dp0
set eventlogname="eventlog-forwarder"
set eventlogfwd=%cwd%\eventlog-forwarder.exe
set eventlogbat=%cwd%\eventlog-forwarder.bat
set eventlogconf=%cwd%\eventlog-forwarder-config.bat

if "%1%" == "usage" (
    :: show eventlog-forwarder.bat usage
    echo usage: %0 [usage daily disable status]
    echo - usage: show eventlog-forwarder.bat usage
    echo - daily: schedule daily eventlog-forwarder.bat task
    echo - disable: delete eventlog-forwarder.bat daily schedule task
    echo - status: show eventlog-forwarder.bat status
    echo - otherwise, run the eventlog-forwarder

) else if "%1%" == "daily" (
    :: set eventlog-forwarder.bat as schedule a daily task
    schtasks /Delete /TN %eventlogname%
    schtasks /Create /SC DAILY /TN %eventlogname% /TR %eventlogbat% /ST 00:00 /RU SYSTEM
) else if "%1%" == "disable" (
    :: delete eventlog-forwarder.bat daily schedule task
    schtasks /Delete /TN %eventlogname%
) else if "%1%" == "status" (
    :: show eventlog-forwarder.bat status"
    schtasks /Query /TN %eventlogname%
    schtasks /Query /TN %eventlogname% /FO LIST /V
) else (
    :: otherwise, run the eventlog-forwarder
    cd %cwd%
    call %eventlogconf%
)

:: make files readonly
attrib +r %eventlogfwd%
attrib +r %eventlogbat%
attrib +r %eventlogconf%
